version: '3.4'
services:
    # nginx-proxy:
    #     image: jwilder/nginx-proxy
    #     container_name: nginx
    #     ports:
    #       - '80:80'
    #       - '443:443'
    #     volumes:
    #       - '/var/run/docker.sock:/tmp/docker.sock:ro'
    #       - './shared/nginx/vhost.d:/etc/nginx/vhost.d'
    #       # - './shared/nginx/certs:/etc/nginx/certs:ro'
    #     networks:
    #       proxy: null
    #       identityserverui:
    #         aliases:
    #           - sts.skoruba.local
    #           - admin.skoruba.local
    #           - admin-api.skoruba.local
    #     restart: always
    # db:
    #   image: postgres
    #   ports:
    #     - 5432:5432
    #   container_name: postgres
    #   environment:
    #     POSTGRES_USERNAME: 'postgres'
    #     POSTGRES_PASSWORD: 'Welcome123$$!'
    #   volumes:
    #     - 'dbdata:/var/lib/postgresql/data'
    #   networks:
    #     identityserverui: null
    avalon.admin:
      # image: avaxxx/avalon.admin
      build:
        context: .
        dockerfile: src/Avalon.Admin/Dockerfile
      container_name: admin
      ports:
        - "44303:80"
      command: dotnet Avalon.Admin.dll /seed
      depends_on:
        - avalon.sts.identity
      volumes:
        - './shared/serilog.json:/app/serilog.json'
        - './shared/identitydata.json:/app/identitydata.json'
        - './shared/identityserverdata.json:/app/identityserverdata.json'
        - './shared/admin/appsettings.json:/app/appsettings.json'
      networks:
        identityserverui: null
    avalon.sts.identity:
      # image: avaxxx/avalon.sts.identity
      build:
        context: .
        dockerfile: src/Avalon.STS.Identity/Dockerfile
      ports:
        - "44310:80"
      container_name: identity
      volumes:
        - './shared/serilog.json:/app/serilog.json'
        - './shared/identity/appsettings.json:/app/appsettings.json'
      networks:
        identityserverui:
          aliases:
            - sts.skoruba.local
volumes:
  dbdata:
    driver: local
networks:
  proxy:
    driver: bridge
  identityserverui:
    driver: bridge

